const products = () =>{
  return [
  {
    id: 1,
    category: "chair",
    name: "Sakarias Armchair",
    price: 392,
    image: "./assets/images/category/1.png",
  },
  {
    id: 2,
    category: "chair",
    name: "baltsar chair",
    price: 299,
    image: "./assets/images/category/2.png",
  },
  {
    id: 3,
    category: "chair",
    name: "Anjay chair",
    price: 519,
    image: "./assets/images/category/3.png",
  },
  {
    id: 4,
    category: "chair",
    name: "Nyantuy chair",
    price: 921,
    image: "./assets/images/category/4.png",
  },
  {
    id: 1,
    category: "chair",
    name: "Sakarias Armchair",
    price: 392,
    image: "./assets/images/category/1.png",
  },
  {
    id: 2,
    category: "chair",
    name: "baltsar chair",
    price: 299,
    image: "./assets/images/category/2.png",
  },
  {
    id: 3,
    category: "chair",
    name: "Anjay chair",
    price: 519,
    image: "./assets/images/category/3.png",
  },
  {
    id: 4,
    category: "chair",
    name: "Nyantuy chair",
    price: 921,
    image: "./assets/images/category/4.png",
  },
  {
    id: 5,
    category: "bed",
    name: "Special Bed 1",
    price: 500,
    image: "./assets/images/category/1.png",
  },
  {
    id: 6,
    category: "bed",
    name: "Special Bed 2",
    price: 600,
    image: "./assets/images/category/2.png",
  },
  {
    id: 7,
    category: "bed",
    name: "Special Bed 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 8,
    category: "bed",
    name: "Special Bed 4",
    price: 800,
    image: "./assets/images/category/4.png",
  },
  {
    id: 5,
    category: "bed",
    name: "Special Bed 1",
    price: 500,
    image: "./assets/images/category/1.png",
  },
  {
    id: 6,
    category: "bed",
    name: "Special Bed 2",
    price: 600,
    image: "./assets/images/category/2.png",
  },
  {
    id: 7,
    category: "bed",
    name: "Special Bed 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 8,
    category: "bed",
    name: "Special Bed 4",
    price: 800,
    image: "./assets/images/category/4.png",
  },
  {
    id: 9,
    category: "Sofa",
    name: "Special Sofa 1",
    price: 300,
    image: "./assets/images/category/1.png",
  },
  {
    id: 10,
    category: "Sofa",
    name: "Special Sofa 2",
    price: 500,
    image: "./assets/images/category/2.png",
  },
  {
    id: 11,
    category: "Sofa",
    name: "Special Sofa 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 12,
    category: "Sofa",
    name: "Special Sofa 4",
    price: 900,
    image: "./assets/images/category/4.png",
  },
  {
    id: 9,
    category: "Sofa",
    name: "Special Sofa 1",
    price: 300,
    image: "./assets/images/category/1.png",
  },
  {
    id: 10,
    category: "Sofa",
    name: "Special Sofa 2",
    price: 500,
    image: "./assets/images/category/2.png",
  },
  {
    id: 11,
    category: "Sofa",
    name: "Special Sofa 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 12,
    category: "Sofa",
    name: "Special Sofa 4",
    price: 900,
    image: "./assets/images/category/4.png",
  },
  {
    id: 13,
    category: "Lamp",
    name: "Special Lamp 1",
    price: 300,
    image: "./assets/images/category/1.png",
  },
  {
    id: 14,
    category: "Lamp",
    name: "Special Lamp 2",
    price: 500,
    image: "./assets/images/category/2.png",
  },
  {
    id: 15,
    category: "Lamp",
    name: "Special Lamp 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 16,
    category: "Lamp",
    name: " Special Lamp 4",
    price: 900,
    image: "./assets/images/category/4.png",
  },
  {
    id: 13,
    category: "Lamp",
    name: "Special Lamp 1",
    price: 300,
    image: "./assets/images/category/1.png",
  },
  {
    id: 14,
    category: "Lamp",
    name: "Special Lamp 2",
    price: 500,
    image: "./assets/images/category/2.png",
  },
  {
    id: 15,
    category: "Lamp",
    name: "Special Lamp 3",
    price: 700,
    image: "./assets/images/category/3.png",
  },
  {
    id: 16,
    category: "Lamp",
    name: " Special Lamp 4",
    price: 900,
    image: "./assets/images/category/4.png",
  },
];
}